sculpin:
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:

    posts:
        permalink: docs/changelog/:year-:month-:filename/
        path: docs/changelog
        enabled: true

    articles:
        type: path
        path: docs/articles
        singular_name: article
        enabled: true
        taxonomies:
            - category
        permalink: pretty

    guides:
        type: path
        path: docs/guides
        singular_name: guide
        enabled: true
        taxonomies:
            - category
            - authors
        permalink: pretty
    8:
        type: path
        path: docs/article/drupal/8
        enabled: true
        permalink: pretty

    local:
        type: path
        path: docs/articles/local
        enabled: true
        permalink: pretty
