sculpin:
    ignore: ["*.swp"]
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:
    posts:
        permalink: docs/changelog/:year/:month/
        path: _changelog
        enabled: true
    docs:
        type: path
        path: _docs
        singular_name: doc
        enabled: true
        taxonomies:
            - categories
            - tags
            - contributors
        permalink: docs/:basename/
    guides:
        type: meta
        taxonomies:
            - categories
            - tags
            - contributors
    videos:
        type: meta
        taxonomies:
            - categories
            - tags
            - contributors

    gettingstartedpages:
        type: path
        path: docs/guides/getting-started
        permalink: pretty
        singular_name: gettingstartedpage
        enabled: true
        layout: guide
        taxonomies:
            - categories
            - tags
            - contributors
    cachecontrolpages:
        type: path
        path: docs/guides/cache-control
        permalink: pretty
        singular_name: cachecontrolpage
        enabled: true
        layout: guide
        taxonomies:
            - categories
            - tags
            - contributors
