sculpin:
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:

    articles:
        type: path
        path: docs/articles
        singular_name: article
        enabled: true
        taxonomies:
            - category
        permalink: pretty

    guides:
        type: path
        path: docs/guides
        singular_name: guide
        enabled: true
        taxonomies:
            - category
            - authors
        permalink: pretty
