sculpin:
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:
    posts:
        permalink: docs/changelog/:year/:month/
        path: _changelog
        enabled: true
    docs:
        type: path
        path: _docs
        singular_name: doc
        enabled: true
        taxonomies:
            - categories
            - tags
            - contributors
        permalink: docs/:basename/
    guides:
        type: path
        path: _guides
        layout: doc
        taxonomies:
            - categories
            - tags
            - contributors
        permalink: docs/guides/:basename/
    videos:
        type: path
        path: _videos
        singular_name: video
        enabled: true
        taxonomies:
            - categories
            - tags
            - contributors
        permalink: docs/videos/:basename/
