# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Pantheon Docs
subtitle: Information for building, launching, and running dynamic sites on the Pantheon Website Management Platform
url: /docs
site_url: https://pantheon.io
assets_version: 2.2

managing: Learn how to manage sites, users, teams, and organizations on Pantheon.
developing: Learn how to build and launch your site on Pantheon.
featured: Get answers to common questions by browsing our most frequently used docs.


#######################################################################################################
# The contributors. Include your info here, under the "contributors" key, using the following template:
#
#  handle:
#      name: Your Name
#      url: http://yourURL.com
#      avatar: http://url.to.a.valid/avatar.jpeg
#      twitter: handle
#      gplus: https://plus.google.com/
#      github: https://github.com/
#      linkedin: https://www.linkedin.com/in/
#      drupal: https://www.drupal.org/u/
#      wordpress: https://profiles.wordpress.org/
#      bio: this is a short bio, it should not be so long, just a quick info that defines you.
#
# Please provide at least "name" and "bio" . The googleplus url is useful to show your contributor info
# on Google search results.
#######################################################################################################

contributors:
  bmackinney:
      name: Brian MacKinney
      url: //brianmackinney.com
      avatar: //www.gravatar.com/avatar/d942a7d4b38d10e4f4ebab9cb148d9f9.png
      twitter: BrianMacKinney
      github: //github.com/bmackinney
      drupal: //www.drupal.org/u/brian-mackinney
      wordpress: //profiles.wordpress.org/brian-mackinney
      linkedin: //www.linkedin.com/in/bmackinney/en
      bio: Instructional Designer, user of Drupal, WordPress, and Pantheon. Baseball, Surfing, and camping with family on weekend.
  calevans:
      name: Cal Evans
      url: //calevans.com
      avatar: //2.gravatar.com/avatar/d6d504bf40dea91cd33027e5bb85f7df
      twitter: calevans
      github: //github.com/calevans
      bio: For the past 13 years Cal has worked with PHP and MySQL on Linux, OSX, and Windows. He has built a variety of projects ranging in size from simple web pages to multi-million dollar web applications. When not banging his head on his monitor, attempting a blood sacrifice to get a particular piece of code working, he enjoys building and managing development teams using his widely imitated but never patented management style of “management by wandering around”.These days, when not working with PHP, Cal can be found working on a variety of projects like CoderFaire. He speaks at conferences around the world on topics ranging from technical talks to motivational talks for developers. If you happen to meet him at a conference, don’t be afraid to buy him a shot of Bourbon.Cal is based in Nashville TN where he is happily married to wife 1.31, the lovely and talented Kathy. Together they have 2 wonderful kids. From blog.calevans.com/epk
  ari:
      name: Ari Gold
      avatar: //secure.gravatar.com/avatar/cde9ea6c0c1cd26527feaa8b4291a85d.jpg  twitter: http://twitter.com/AriAtPantheon
      github: //github.com/ari-gold
      drupal: //www.drupal.org/user/329006/
      bio:  Enterprise Onboarding Manager
  jessifischer:
      name: Jessi Fischer
      avatar: //pantheon.io/sites/default/files/styles/540x540_top/public/JessiNew.jpg
      github: //github.com/JessiFischer
      drupal: //www.drupal.org/u/jayelebun
      linkedin: //www.linkedin.com/in/jessifischer
      bio: Enterprise Onboarding Manager
  erikmathy:
      name: Erik Mathy
      avatar: //www.gravatar.com/avatar/0e9285db4e5bdbb3356306ddb55483d8.png
      twitter: 1gearnobrains
      linkedin: //www.linkedin.com/pub/erik-mathy/28/b51/627/en
      bio: Enterprise Onboarding Manager
  populist:
      name: Matt Cheney
      avatar: //avatars1.githubusercontent.com/u/520521
      twitter: populist
      bio: Website developer extraordinaire
  joshkoenig:
      name: Josh Koenig
      avatar: //pantheon.io/sites/default/files/styles/540x540_top/public/JoshNew.jpg
      twitter: outlandishjosh
      linkedin: //www.linkedin.com/in/joshkoenig
      bio: Co-Founder & Head of Developer Experience
  kate:
      name: Kate Kligman
      avatar: //pantheon.io/sites/default/files/styles/540x540_top/public/Kate_Kligman.jpg
      twitter: KateKligman
      linkedin: //www.linkedin.com/in/katekligman
      bio: Open source contributor, indie game developer, retro gamer
  iameap:
      name: Eric Peterson
      url: //www.eric.pe/terson
      avatar: //s.gravatar.com/avatar/0cd9fdc3a5e346d8fd7b74c527a93346?s=300
      twitter: iamEAP
      gplus: //plus.google.com/+iamEAP
      github: //github.com/iamEAP
      linkedin: //www.linkedin.com/in/iamEAP
      drupal: //www.drupal.org/u/iamEAP
      bio: Marketing engineering
  rvtraveller:
      name: Brian Thompson
      avatar: //www.gravatar.com/avatar/7260ed8618de5108bb3ddc6e6dea88f2.png
      twitter: rvtraveller26
      linkedin: //www.linkedin.com/in/1briant
      bio: Developer by day, techie and gamer by night, camper on the weekends
  eeeschwartz:
    name: Erik Schwartz
    url: //erikschwartz.net
    avatar: //s.gravatar.com/avatar/bd808f082e76f519e9dcfe6ae8a2e7ca?s=80
    twitter: eeeschwartz
    github: //github.com/eeeschwartz/
    linkedin: //www.linkedin.com/in/eeeschwartz
    bio: Civic developer, human centered!
  suzannealdrich:
      name: Suzanne Aldrich
      url: //suzanne.link
      avatar: //s.gravatar.com/avatar/cca6b0cbfbc6ed1804e381d66d012f02?s=300
      twitter: SuzanneAldrich
      github: //github.com/suzannealdrich
      linkedin: //www.linkedin.com/in/suzannealdrich
      drupal: //www.drupal.org/u/suzanne.aldrich
      bio: Web technologist specializing in security, performance, and usability.
  mrfelton:
    name: Tom Kirkpatrick
    url: //www.systemseed.com
    avatar: //avatars2.githubusercontent.com/u/200251?v=3&s=400
    twitter: mrfelton
    github: //github.com/mrfelton
    drupal: //www.drupal.org/u/mrfelton
    bio: After many years of developing custom web solutions and CMS systems I realised the error of my ways and decided to pool all of my efforts into making Drupal a better CMS platform. These days, I eat, sleep and breath Drupal.
  afragen:
    name: Andy Fragen
    url: //thefragens.com
    twitter: andyfragen
    github: //github.com/afragen
    bio: I am a surgeon, husband and father and I try my best to juggle all while keeping perspective on what’s important. BTW, importance is listed in reverse order.
