name: PR Links

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Link Checker
        uses: lycheeverse/lychee-action@97189f2c0a3c8b0cb0e704fd4e878af6e5e2b2c5 # v1.7.0
        with:
          args: >
            --accept 200,204,206,401,403,421,429
            --verbose
            --exclude http://localhost:8000/
            "*.md"
            "source/**/*.md"
            --timeout 20
          fail: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
