name: Spam
on: issue_comment
jobs:
  mark-as-spam: # runs when it detects this as a comment: [/spam]
    name: mark as spam
    runs-on: ubuntu-latest
    steps:
      - name: close issue
        uses: balevine/mark-as-spam@9f9b68e6eaf35c84c5487b397182e792920039ba # production 2019-10-10T19:38:12Z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
